###
GET http://localhost:3000

###
GET http://localhost:3000/pets

###
GET http://localhost:3000/pets/3

###
POST http://localhost:3000/pets
Content-Type: application/json

{
    "age": 3,
    "kind": "parakeet",
    "name": "Cornflake"
}

###
PATCH http://localhost:3000/pets/3
Content-Type: application/json

{
    "name": "Fido"
}

###
DELETE http://localhost:3000/pets/3